name: CI Pipeline Demo  #

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4  # An action to clone your repo's code onto the runner

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify your project's required language version

    - name: Install dependencies
      run: npm install  # Command to install project dependencies

    - name: Run tests
      run: npm test  # Command to run automated tests
