{
 "title": "Flask Application Metrics",
 "tags": [
  "flask",
  "python"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per second (200 OK)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{`{{ path }}`}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"200\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "HTTP {{`{{ status }}`}}"
    }
   ]
  },
  {
   "title": "Average request duration [s]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[30s]) / rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{`{{ path }}`}}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[30s]))",
     "legendFormat": "{{`{{ path }}`}}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{status=\"200\",le=\"0.25\"}[30s]) / ignoring (le) increase(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{`{{ path }}`}}"
    }
   ]
  }
 ]
}